[contexts.py]
  [test_locale_override_applies_to_existing_sandbox]
    bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1983807
    expected: FAIL
